# --- !Ups

DROP TABLE ticket_history;

CREATE TABLE ticket_history (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL,
    ticket_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    project_id INT UNSIGNED NOT NULL,
    old_project_id INT UNSIGNED NOT NULL,
    priority_id INT UNSIGNED NOT NULL,
    old_priority_id INT UNSIGNED NOT NULL,
    resolution_id INT UNSIGNED,
    old_resolution_id INT UNSIGNED,
    proposed_resolution_id INT UNSIGNED,
    old_proposed_resolution_id INT UNSIGNED,
    assignee_id INT UNSIGNED,
    old_assignee_id INT UNSIGNED,
    attention_id INT UNSIGNED,
    old_attention_id INT UNSIGNED,
    reporter_id INT UNSIGNED NOT NULL,
    old_reporter_id INT UNSIGNED NOT NULL,
    severity_id INT UNSIGNED NOT NULL,
    old_severity_id INT UNSIGNED NOT NULL,
    status_id INT UNSIGNED NOT NULL,
    old_status_id INT UNSIGNED NOT NULL,
    type_id INT UNSIGNED NOT NULL,
    old_type_id INT UNSIGNED NOT NULL,
    position INT,
    old_position INT,
    summary VARCHAR(255) NOT NULL,
    old_summary VARCHAR(255) NOT NULL,
    description TEXT,
    old_description TEXT,
    date_occurred DATETIME NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (ticket_id) REFERENCES tickets(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (assignee_id) REFERENCES users(id),
    FOREIGN KEY (old_assignee_id) REFERENCES users(id),
    FOREIGN KEY (attention_id) REFERENCES users(id),
    FOREIGN KEY (old_attention_id) REFERENCES users(id),
    FOREIGN KEY (project_id) REFERENCES projects(id),
    FOREIGN KEY (old_project_id) REFERENCES projects(id),
    FOREIGN KEY (priority_id) REFERENCES ticket_priorities(id),
    FOREIGN KEY (old_priority_id) REFERENCES ticket_priorities(id),
    FOREIGN KEY (resolution_id) REFERENCES ticket_resolutions(id),
    FOREIGN KEY (old_resolution_id) REFERENCES ticket_resolutions(id),
    FOREIGN KEY (reporter_id) REFERENCES users(id),
    FOREIGN KEY (old_reporter_id) REFERENCES users(id),
    FOREIGN KEY (severity_id) REFERENCES ticket_severities(id),
    FOREIGN KEY (old_severity_id) REFERENCES ticket_severities(id),
    FOREIGN KEY (status_id) REFERENCES workflow_statuses(id),
    FOREIGN KEY (old_status_id) REFERENCES workflow_statuses(id),
    FOREIGN KEY (type_id) REFERENCES ticket_types(id),
    FOREIGN KEY (old_type_id) REFERENCES ticket_types(id)
) ENGINE InnoDB CHARACTER SET utf8 COLLATE utf8_bin;

# --- !Downs