#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Do you like debian?
db_input medium emperor/dbhost || true
db_input medium emperor/dbname || true
db_input high emperor/dbuser || true
db_input high emperor/dbpass || true
db_go
