#!/bin/sh
set -e

case "$1" in
  remove)
    # Remove logs
    rm -rf /var/log/emperor

    # remove **only** empty data dir
    rmdir -p --ignore-fail-on-non-empty /var/lib/emperor
  ;;

  purge)
    # Remove service
    update-rc.d emperor remove >/dev/null || true

    # Remove logs, config and data
    rm -rf /var/log/emperor /var/lib/emperor /etc/emperor

    # Remove user/group
    userdel emperor 2>/dev/null || true

    # Source debconf library.
    . /usr/share/debconf/confmodule
    # Remove my changes to the db.
    db_purge
  ;;

  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    echo "$0 called with unknown argument $1" >&2
    exit 1
  ;;
esac
